# Generated by Django 3.1.2 on 2022-08-03 10:03

import abcApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_Text', models.CharField(blank=True, max_length=500, null=True)),
                ('request_Obj', models.CharField(max_length=20)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isPerm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('visit_date', models.DateField()),
                ('responded', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50, null=True)),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_name', models.CharField(max_length=20)),
                ('child_object', models.FileField(upload_to=abcApp.models.getUpload, validators=[django.core.validators.FileExtensionValidator(['mp3', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('likes', models.PositiveIntegerField(default=0)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatedBy', models.CharField(default='Anonymous', max_length=50)),
                ('donation_type', models.CharField(max_length=50)),
                ('delivery_date', models.DateField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcApp.request')),
            ],
        ),
    ]
