# Generated by Django 3.1.2 on 2022-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatedBy', models.CharField(default='Anonymous', max_length=20)),
                ('nric', models.CharField(max_length=10, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='donatedBy',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
