# Generated by Django 3.1.2 on 2022-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcApp', '0002_auto_20220804_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydonation',
            name='yearly',
            field=models.BooleanField(default=False),
        ),
    ]
